### ISSUE TITLE
Worker Timeout

### ISSUE THREAD

**Issue by JXGA** [milesmcc/shynet#11]
Hi there, 

I may well be doing something wrong, but having issues with timeouts.. System works fine for a couple of minutes, then randomly stops - this halts fetching the file from the server and makes web pages hang. 
I am running an unusual setup, using two VMs. One is my main ingress via a Caddy reverse proxy, which then sends the request internally to the ShyNet server which is on a different machine. 
I don't think this should affect operation - any thoughts?

> Launching Shynet web server...
> [2020-04-28 21:45:16 +0000] [1] [INFO] Starting gunicorn 20.0.4
> [2020-04-28 21:45:16 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
> [2020-04-28 21:45:16 +0000] [1] [INFO] Using worker: sync
> [2020-04-28 21:45:16 +0000] [8] [INFO] Booting worker with pid: 8
> [2020-04-28 21:45:16 +0000] [9] [INFO] Booting worker with pid: 9
> [2020-04-28 21:45:16 +0000] [10] [INFO] Booting worker with pid: 10
> [2020-04-28 21:47:16 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
> [2020-04-28 22:47:16 +0100] [8] [INFO] Worker exiting (pid: 8)
> [2020-04-28 21:47:16 +0000] [11] [INFO] Booting worker with pid: 11
> [2020-04-28 21:47:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
> [2020-04-28 22:47:18 +0100] [10] [INFO] Worker exiting (pid: 10)
> [2020-04-28 21:47:19 +0000] [12] [INFO] Booting worker with pid: 12

Thanks in advance - this project looks really promising !

**Comment by milesmcc** [comment]
Hmm, this definitely isn't expected behavior, but also not something I've been able to replicate. Would you mind posting a redacted version of your environment file? I have a feeling this might be related to a misconfigured cache.

**Comment by milesmcc** [comment]
[This Gunicorn issue](https://github.com/benoitc/gunicorn/issues/1801) may be related, though it's still unclear why this would cause requests to hang.

**Comment by JXGA** [comment]
.env contents:

> # Database
> DB_NAME=xyz
> DB_USER=xyz
> DB_PASSWORD=xyz
> DB_HOST=xyz
> DB_PORT=xyz
> 
> # General Django settings
> DJANGO_SECRET_KEY=xyz
> # Don't leak error details to visitors, very important
> DEBUG=False
> # Unless you are using an external Celery task queue, make sure this
> # is set to True.
> CELERY_TASK_ALWAYS_EAGER=True 
> # For better security, set this to your deployment's domain. Comma separated.
> ALLOWED_HOSTS=*
> # Set to True (capitalized) if you want people to be able to sign up for your Shynet instance (not recommended)
> SIGNUPS_ENABLED=False
> # Change as required
> TIME_ZONE=Europe/Dublin
> # Set to "False" if you will not be serving content over HTTPS
> SCRIPT_USE_HTTPS=True

All seems okay with the connection between Caddy & ShyNet machines - other services are working fine... 
Have your tests all worked fine with 3 workers?

**Comment by JXGA** [comment]
> [This Gunicorn issue](https://github.com/benoitc/gunicorn/issues/1801) may be related, though it's still unclear why this would cause requests to hang.

There was a response in there about a security group - I added another rule, and the logs have calmed down a bit (there was one that broke through in the mean time) - so it might have been me missing a step on my end. 
I’ll get back to you tomorrow with an update. Thanks for the help thus far!

**Comment by milesmcc** [comment]
Let me know what you find. The worker threads are intended to be somewhat disposable, so they'll often die for no real reason. Why Gunicorn prints the log as "CRITICAL" is beyond me.

Either way, let me know what you find w.r.t. the security rules and I'll improve the documentation so that others in the future don't have the same issue.

**Comment by JXGA** [comment]
No change here I'm afraid, workers still hanging and causing the site to become unresponsive. 
As I can access the ShyNet UI, I assume all the security rules are correctly set on the instances - otherwise I wouldn't get a connection to it. 
Also, I'm not actually getting any results on the ShyNet UI for any hits on the site. When the site isn't hanging, it's showing a 200 connection for the GET collecting the js, then a 200 for OPTIONS, but no responses for the POST or any subsequent OPTIONS. 
Any thoughts?

**Comment by doenietzomoeilijk** [comment]
It appears like I'm running into the same issue. UI is responsive and works, but the tracking just hangs and there's critical worker timeouts in the logs. Once I've started a tracking request, the UI starts lagging as well. 

Fwiw, I'm running Shynet in a docker container (`:latest`)and Postgres (`:12`)in an other, both started from docker-compose. There's also an Adminer instance running, through which I can reach and operate the database just fine. No Redis in the mix just yet, but from JXGA's comments, I don't think that'll solve things.

Anything useful I can do to help troubleshoot this? If I enable debug logs, where do those end up?

**Comment by milesmcc** [comment]
Alright, the information about the hanging POSTs is very helpful: it made me realize that I've seen this issue before! (Unfortunately, I don't remember exactly how I solved it, but I believe it was a configuration change.)

I am able to replicate this issue by turning `CELERY_TASK_ALWAYS_EAGER` to `False` (or by omitting it entirely), but can't seem to figure out a way to replicate this by other means.

@doenietzomoeilijk—would you be able to post a redacted version of your environment as well?

**Comment by doenietzomoeilijk** [comment]
@milesmcc Sure thing!

Here's docker-compose.yml:

```yaml
version: '2'
services:
  app:
    image: milesmcc/shynet:latest
    container_name: shynet
    env_file:
      - .env
    networks:
      - shynet_net
    ports:
      - 18085:8080
  db:
    image: postgres:12
    env_file:
      - .env
    networks:
      - shynet_net
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - shynet_postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - shynet_net
    ports:
      - 18086:8080
volumes:
  shynet_postgres_data: ~
networks:
  shynet_net:
    driver: bridge
```

And this is the .env file:

```
DJANGO_SECRET_KEY=REDACTED
ALLOWED_HOSTS=*
TIME_ZONE=Europe/Amsterdam
DEBUG=True
SIGNUPS_ENABLED=False
DB_USER=shynet
DB_PASSWORD=REDACTED
DB_NAME=shynet
DB_HOST=db
MAIL_HOST=REDACTED
SERVER_EMAIL=noreply@REDACTED
```

That's it, basically. No mention of Celery, although I could give that a go.

Anything else that could be interesting?
