### ISSUE TITLE
Data not populating in Shynet Dashboard [QUESTION-label didn't apply]

### ISSUE THREAD

**Issue by rastacalavera** [milesmcc/shynet#110]
I really like the sound of this project and was excited to try it out. The installation was a breeze other than I tried to install it on an arm server first and didn't realize it was x86 only.

I am not seeing any traffic on the site that I wish shynet was tracking. Here is my current setup:
1. My blog runs using HUGO (a static website generator) and is hosted on Gitlab. It has SSl through letsencrypt
2. Shynet runs on my private home server (Ubuntu 20.04, installed with docker) does not have ssl. This is a backup server that's on an x86 machine. My "main server" is a raspberrypi 4 that is running LSIO's swag container. I installed shynet without ssl just for testing it out first. My home router is forwarding ports 80 and 443 to the Pi so I i created the following config in nginx to route traffic to shynet instance
```
server {
    listen 80;
    listen [::]:80;

    server_name shynet.*;

    client_max_body_size 0;

    location / {

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app LOCAL IP OF MY x86 SERVER;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```

My snipit was generated and looks something like this (some information redacted)
```
<noscript><img src="http://FAKEWEBSITE.com/ingress/STINGOFTHINGS/pixel.gif"></noscript> <script src="http://FAKEWEBSITE.com/ingress/STRINGOFTHINGS/script.js"></script> 
```
I read the documentation (which is well done! Thanks for your hard work!!) and the trouble shooting so here is where I am at now:

1. HUGO doesn't natively show the html since everything is in markdown. I looked at my site source code using Fire fox and I did see the `<noscript>` tag directly below the final `<p>`. I am guessing this occurs because I just pasted it as the last line in my markdown file. About a 100 lines below that in the source I see the `</body>` tag. Does my script have to be **right after that tag** for it to work properly? If so, any idea on how to do that in HUGO?

2. When I log in to shynet, the first main heading is `example.com` which is confusing to me because I replace that text with my own domain in the `nginx.conf` file and made sure to put my domain in the `docker exec -it shynet_main ./manage.py hostname FAKEWEBSITE.com` command.

The docker-compose file pulls an image for nginx but is it expected to be installed only through APT rather than docker? When I've used the linuxserver.io swag image, it creates a volume for nginx where the `sites-available` stuff is and I don't see anything like that in this compose file. Here is my compose file
```
version: '3'
services:
  shynet:
    container_name: shynet_main
    image: milesmcc/shynet:latest
    restart: unless-stopped
    expose:
      - 8080
    env_file:
      # Create a file called '.env' if it doesn't already exist.
      # You can use `TEMPLATE.env` as a guide.
      - .env
    environment:
      - DB_HOST=db
    networks:
      - internal
    depends_on:
      - db
  db:
    container_name: shynet_database
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    volumes:
      - shynet_db:/var/lib/postgresql/data
    networks:
      - internal
  webserver:
    container_name: shynet_webserver
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf    
    ports:
      - 8080:80
    depends_on:
      - shynet
    networks:
      - internal
volumes:
  shynet_db:
networks:
  internal:
```
and the contents of my working directory:
```
.                   docker-compose.yml  .github     images      package.json       README.md
..                  Dockerfile          .gitignore  kubernetes  package-lock.json  shynet
app.json            .env                GUIDE.md    LICENSE     Pipfile            TEMPLATE.env
CODE_OF_CONDUCT.md  .git                heroku.yml  nginx.conf  Pipfile.lock       tests
```
