### ISSUE TITLE
Sidebar shows and hides on page loaded

### ISSUE THREAD

**Issue by ndaidong** [milesmcc/shynet#130]
I could not see the sidebar, it appears and then disappears suddenly. 
Running with docker-compose, tested with the latest image and 0.8.2, 0.8.1, 0.8.0, 0.7.3

https://youtu.be/8B4Jh6Exc8o

**Comment by CasperVerswijvelt** [comment]
Do you see any errors or something in the console? (right click anywhere on the page, click `inspect` and then go to the `console` tab)

**Comment by ndaidong** [comment]
There is just a 404 error as it could not load icon from duckduckgo which I think that it does not relate to this issue. 

![Screenshot from 2021-04-26 18-30-04](https://user-images.githubusercontent.com/1809619/116075714-79f41080-a6bd-11eb-816e-a78671901a23.png)

**Comment by CasperVerswijvelt** [comment]
Okay, maybe you can check in `inspector` tab to see if you can find the element with id `navMenuExpanded`, select it and check the styling.  In my case, where it is working correctly I see this (see screenshot). The `display: block ` rule in the `.md:block` should be active. If I manually disable that rule globally I see exactly the same view as what you're seeing, so probably something is interfering with that css rule in your instance or browser. Did you try visiting the site in another browser?

![image](https://user-images.githubusercontent.com/25928551/116085043-b5331700-a69e-11eb-931a-71f2b7171801.png)

**Comment by milesmcc** [comment]
That's so strange—I'm not sure I've ever seen anything like this. Also not sure what could have caused this issue...

**Comment by ndaidong** [comment]
@CasperVerswijvelt you're right. That block is disabled.

![Screenshot from 2021-04-27 09-54-31](https://user-images.githubusercontent.com/1809619/116177780-a308b580-a73e-11eb-8514-d5a6cbcf29af.png)

I've tested on Firefox 88, Vivaldi 3.72 and Opera 75. However I have only EndeavourOS to try.

This is my docker-compose.yaml :

```
version: '3'
services:
  db:
    image: postgres:13.2-alpine
    container_name: shynet-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /storage/data/postgres:/var/lib/postgresql/data
    restart: always

  shynet:
    image: milesmcc/shynet:latest
    container_name: shynet
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - 18080:8080
    restart: unless-stopped
```

And .env file:


```
DB_NAME=shynetdb
DB_USER=shynet
DB_PASSWORD=my_very_complex_password
DB_HOST=db
DB_PORT=5432

EMAIL_HOST_USER=my_smtp_username
EMAIL_HOST_PASSWORD=my_smtp_password
EMAIL_HOST=my_smtp_server
EMAIL_PORT=587
EMAIL_USE_SSL=True

DJANGO_SECRET_KEY=TzY2gJRNmre...

ALLOWED_HOSTS=*

ACCOUNT_SIGNUPS_ENABLED=False

ACCOUNT_EMAIL_VERIFICATION=none

TIME_ZONE=Asia/Ho_Chi_Minh

SCRIPT_USE_HTTPS=False

SCRIPT_HEARTBEAT_FREQUENCY=5000

SESSION_MEMORY_TIMEOUT=1800

ONLY_SUPERUSERS_CREATE=True

PERFORM_CHECKS_AND_SETUP=True

PORT=8080

SHOW_SHYNET_VERSION=True

SHOW_THIRD_PARTY_ICONS=True

BLOCK_ALL_IPS=False

AGGRESSIVE_HASH_SALTING=True
```
